def atof(): pass
def atoi(): pass
def atol(): pass
def capitalize(): pass
def count(): pass
def expandtabs(): pass
def find(): pass
def join(): pass
def joinfields(): pass
def lower(): pass
def lstrip(): pass
def maketrans(): pass
def replace(): pass
def rfind(): pass
def rstrip(): pass
def split(): pass
def splitfields(): pass
def strip(): pass
def swapcase(): pass
def translate(): pass
def upper(): pass
lowercase = 'abcdefghijklmnopqrstuvwxyz'
uppercase = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
whitespace = '\t\n\x0b\x0c\r '
