def acos(): pass
def acosh(): pass
def asin(): pass
def asinh(): pass
def atan(): pass
def atanh(): pass
def cos(): pass
def cosh(): pass
def exp(): pass
def isinf(): pass
def isnan(): pass
def log(): pass
def log10(): pass
def phase(): pass
def polar(): pass
def rect(): pass
def sin(): pass
def sinh(): pass
def sqrt(): pass
def tan(): pass
def tanh(): pass
e = 2.718281828459045
pi = 3.141592653589793
